export enum Routes {
  Mailing = '/mailing',
  Home = '/',
  Parsers = '/parsers',
  ParsersActivities = '/parsers/activities',
  ParsersParticipants = '/parsers/participants',
  ParsersGeolocation = '/parsers/geolocation',
  Login = '/login',
  Registration = '/registration',
  Recovery = '/recovery',
  Dashboard = '/dashboard',
  Base = '/base',
  Finance = '/finance',
  Reports = '/reports',
  Inviting = '/inviting',
  Tariffs = '/tariffs',
  HomeTariffs = '/home/tariffs',
  Documents = '/documents',
  Profile = '/profile',
}
